version: '3'

services:
  client:
    build: ./client
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - front-tier
      - back-tier

  server:
    build: .
    command: npm run server
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    volumes:
       - .:/app
       - /app/node_modules
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - front-tier
      - back-tier

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="user" 
      - MONGODB_PASS="pass"
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    networks:
      - back-tier
    # command: mongod --smallfiles --logpath=/dev/null # --quiet

networks:
  front-tier:
  back-tier: